#!/usr/bin/env python3
"""Create an OSDP VCI trust anchor record from an X.509 certificate.

The script intentionally emits JSON rather than prose so the output can be
checked by tests or pasted into proposal notes. The top-level fields are ordered
for people first: a short summary, then the exact record metadata, then source
certificate details.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.x509.oid import ExtensionOID


MAX_RECORD_LEN = 0x0240


def encode_len(length: int) -> bytes:
    """Encode a BER definite length.

    The VCI trust anchor record is BER-TLV. Short lengths use one byte; larger
    lengths use the standard long-form length encoding. Indefinite lengths are
    never generated by this tool.
    """
    if length < 0:
        raise ValueError("negative length")
    if length < 0x80:
        return bytes([length])
    raw = length.to_bytes((length.bit_length() + 7) // 8, "big")
    return bytes([0x80 | len(raw)]) + raw


def encode_tlv(tag: bytes, value: bytes) -> bytes:
    """Build one BER-TLV object."""
    return tag + encode_len(len(value)) + value


def load_certificate(path: Path) -> x509.Certificate:
    """Load a PEM or DER X.509 certificate from disk."""
    data = path.read_bytes()
    if b"-----BEGIN CERTIFICATE-----" in data:
        return x509.load_pem_x509_certificate(data)
    return x509.load_der_x509_certificate(data)


def key_description(public_key: object) -> str:
    """Return the compact algorithm label used in JSON summaries."""
    if isinstance(public_key, rsa.RSAPublicKey):
        return f"RSA-{public_key.key_size}"
    if isinstance(public_key, ec.EllipticCurvePublicKey):
        return f"EC-{public_key.curve.name}"
    return public_key.__class__.__name__


def validate_public_key(public_key: object) -> None:
    """Enforce the key types and sizes supported by the proposal."""
    if isinstance(public_key, rsa.RSAPublicKey):
        if public_key.key_size > 4096:
            raise ValueError(f"unsupported RSA key size: {public_key.key_size}")
        return
    if isinstance(public_key, ec.EllipticCurvePublicKey):
        if public_key.curve.name not in {"secp256r1", "secp384r1"}:
            raise ValueError(f"unsupported EC curve: {public_key.curve.name}")
        return
    raise ValueError(f"unsupported public key type: {public_key.__class__.__name__}")


def wrap_hex(data: bytes, width: int = 64) -> list[str]:
    """Return upper-case hex split into readable lines."""
    text = data.hex().upper()
    return [text[index : index + width] for index in range(0, len(text), width)]


def build_record(cert: x509.Certificate) -> tuple[bytes, dict[str, object]]:
    public_key = cert.public_key()
    validate_public_key(public_key)

    # The record selector is the same value the PD later matches against CVC
    # tag 42: the leftmost 8 bytes of the content-signing certificate SKI.
    ski = cert.extensions.get_extension_for_oid(ExtensionOID.SUBJECT_KEY_IDENTIFIER).value.digest
    iin = ski[:8]

    # Store the complete X.509 SubjectPublicKeyInfo so RSA and EC roots can be
    # represented without forcing them into a NIST SP 800-73 Intermediate CVC.
    spki = public_key.public_bytes(
        serialization.Encoding.DER,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    # The compact record contains only the profile, selector, and public key.
    body = b"".join(
        [
            encode_tlv(b"\x80", b"\x01"),
            encode_tlv(b"\x42", iin),
            encode_tlv(b"\x7f\x49", spki),
        ]
    )
    record = encode_tlv(b"\x7f\x50", body)
    if len(record) > MAX_RECORD_LEN:
        raise ValueError(f"trust anchor record is {len(record)} bytes, maximum is {MAX_RECORD_LEN}")

    summary = {
        "summary": {
            "status": "created",
            "message": (
                f"Created {len(record)} byte VCI trust anchor record for "
                f"{key_description(public_key)} anchor {iin.hex().upper()}."
            ),
        },
        "trust_anchor_record": {
            "profile": "0x01",
            "iin": iin.hex().upper(),
            "algorithm": key_description(public_key),
            "record_length": len(record),
            "maximum_record_length": MAX_RECORD_LEN,
            "spki_length": len(spki),
            "record_hex_lines": wrap_hex(record),
        },
        "source_certificate": {
            "subject": cert.subject.rfc4514_string(),
            "serial_number": hex(cert.serial_number),
            "subject_key_identifier": ski.hex().upper(),
        },
    }
    return record, summary


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("certificate", type=Path, help="X.509 content-signing certificate in PEM or DER")
    parser.add_argument("output", type=Path, help="Output binary trust anchor record")
    args = parser.parse_args()

    try:
        cert = load_certificate(args.certificate)
        record, summary = build_record(cert)
        args.output.write_bytes(record)
        summary["output_file"] = str(args.output)
        print(json.dumps(summary, indent=2))
        return 0
    except Exception as exc:  # noqa: BLE001 - command-line diagnostic
        print(json.dumps({"error": str(exc)}, indent=2), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
