#!/usr/bin/env python3
"""Render the verified CRAUTH wire example."""
import json

from check_crauth_examples import ROOT, verify
from render_sm_vci_examples import dump


def render(document):
    verify(document)
    out = ["% Generated by scripts/render_crauth_examples.py; do not hand edit.",
           r"\begin{SimpleTable}{CRAUTH command and reply exchange}{3}",
           r"{|L{0.19\SimpleUsableWidth}|L{0.52\SimpleUsableWidth}|L{0.29\SimpleUsableWidth}|}",
           r"{\TableHeaderCell{Message} & \TableHeaderCell{Packet bytes (hex)} & \TableHeaderCell{Notes}}"]
    for row in document["cases"][0]["exchanges"]:
        for field, actor in (("request", "ACU"), ("reply", "PD")):
            raw = bytes.fromhex(row[field])
            payload = raw[5:-2]
            name = {0xA5: "CRAUTH", 0x82: "CRAUTHR", 0x60: "POLL", 0x40: "ACK"}[payload[0]]
            if payload[0] in (0xA5, 0x82):
                total, offset, size = [int.from_bytes(payload[i:i + 2], "little") for i in (1, 3, 5)]
                note = f"Total 0x{total:04X}; offset 0x{offset:04X}; fragment 0x{size:04X}."
                if payload[0] == 0xA5 and offset == 0:
                    note += " Format marker only."
            elif payload[0] == 0x60:
                note = "Poll for the result."
            else:
                note = "Fragment accepted." if bytes.fromhex(row["request"])[5] == 0xA5 else "No completion pending."
            out.append(actor + r"\newline \texttt{" + name + "} & " + dump(raw) + " & " + note + r" \\\hline")
    out += [r"\end{SimpleTable}", r"\begin{SimpleTable}{Modeled failure completions}{3}",
            r"{|L{0.24\SimpleUsableWidth}|L{0.42\SimpleUsableWidth}|L{0.34\SimpleUsableWidth}|}",
            r"{\TableHeaderCell{Failure} & \TableHeaderCell{Packet bytes (hex)} & \TableHeaderCell{ACU action}}"]
    for case, title, note in zip(document["cases"][1:],
            ("Credential rejection", "Failure after a data fragment"),
            ("PIVERROR 0x1023 (security conditions unmet), SW1/SW2 0x6982. End the request.",
             "PIVERROR 0x0002 (smart-card timeout). Discard the partial response.")):
        raw = next(bytes.fromhex(r["reply"]) for r in case["exchanges"] if bytes.fromhex(r["reply"])[5] == 0x8A)
        out.append(title + " & " + dump(raw) + " & " + note + r" \\\hline")
    return "\n".join(out + [r"\end{SimpleTable}", ""])


if __name__ == "__main__":
    document = json.loads((ROOT / "worked-examples/crauth/examples.json").read_text())
    (ROOT / "tables/crauth-worked-examples.tex").write_text(render(document))
